In [1]:
import sys
print(sys.executable)

/home/arijit/miniconda3/envs/ml/bin/python


In [2]:
import numpy as np

## List 

#### multiplying a list

In [3]:
a = [1,2,3,4,5]
a * 2  # This will repeat the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
squared = [i**2 for i in a] # This will create a new list with squared values
squared

[1, 4, 9, 16, 25]

#### now let's move to numpy, where everything is array and we can easily find out the shape

In [5]:
a = [1,2,3,4,5] # 1 dimensional list
b = np.array(a) # 1 dimensional numpy array
print(b)
b.shape

[1 2 3 4 5]


(5,)

In [6]:
c = [[1,2,3],[4,5,6],[7,8,9]] # 2 dimensional list
d = np.array(c) # 2 dimensional numpy array
print(d)
d.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [7]:
b ** 2 # Element-wise squaring of numpy array

array([ 1,  4,  9, 16, 25])

#### some tricks

In [8]:
arr = np.zeros((3,4)) # Create a 3x4 array of zeros
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.ones((3,4)) # Create a 3x4 array of ones
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.full((2,3), 7) # Create a 2x3 array filled with the value 7
arr

array([[7, 7, 7],
       [7, 7, 7]])

In [11]:
arr = np.eye(4) # Create a 4x4 identity matrix
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
arr = np.random.random((2,3)) # Create a 2x3 array with random values
arr

array([[0.89893145, 0.23997019, 0.40030728],
       [0.2896466 , 0.6692427 , 0.31852583]])

In [13]:
arr = np.random.rand(2,3) # Create a 2x3 array with random values between 0 and 1
arr

array([[0.25414432, 0.2666916 , 0.36339828],
       [0.56902583, 0.36933386, 0.92888261]])

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
brr = arr[:2] # Slicing: Get the first two rows
brr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
brr = arr[:, 1:] # Slicing: Get all rows, columns from index 1 onwards
brr

array([[2, 3],
       [5, 6],
       [8, 9]])

In [17]:
print(np.array([arr[0,0], arr[1,1], arr[2,2]])) # Accessing diagonal elements

[1 5 9]


## Real time image work with numpy

In [18]:
import imageio.v2 as imageio
img = imageio.imread('/home/arijit/Downloads/1.jpg')
print(img)
print(img.shape, img.dtype)

[[[176  84  61]
  [210 137  94]
  [190 152  67]
  ...
  [148 232  46]
  [152 241  39]
  [146 238  29]]

 [[170  90  53]
  [255 213 152]
  [250 221 119]
  ...
  [161 219  39]
  [171 233  44]
  [177 243  47]]

 [[177 120  53]
  [250 209 117]
  [235 224  83]
  ...
  [217 222  60]
  [208 217  50]
  [194 206  36]]

 ...

 [[197 215  31]
  [171 166   4]
  [216 161  42]
  ...
  [162  31 189]
  [137  26 164]
  [152  51 179]]

 [[210 203  52]
  [181 158  26]
  [214 164  67]
  ...
  [183  20 205]
  [143  27 180]
  [154  62 199]]

 [[200 180  45]
  [172 143  25]
  [186 138  53]
  ...
  [190  12 210]
  [148  30 192]
  [157  68 210]]]
(270, 480, 3) uint8


In [19]:
img_tinted = (img * np.array([0, 0, 1], dtype=np.uint8)).astype(np.uint8) # Tint the image blue
imageio.imwrite('/home/arijit/Downloads/1_tinted.jpg', img_tinted)

In [20]:
img2 = imageio.imread('/home/arijit/Downloads/2.jpg')
img2_tinted = (img2 * np.array([1, 0, 0], dtype=np.uint8)).astype(np.uint8) # Tint the image red
imageio.imwrite('/home/arijit/Downloads/2_tinted.jpg', img2_tinted)